theme: jekyll-theme-cayman
show_downloads: true
name: Explorio
description: A game....with a hint of exploration!
avatar: https://png.icons8.com/metro/1600/source-code.png
logo: https://png.icons8.com/metro/1600/source-code.png
